[package]
name = "untitled1"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.13"
tungstenite = "0.24.0"
url = "2.5.3"
shared = { path = "../shared" }
serde_json = "1.0.133"
glam = "0.29.2"
get_if_addrs = "0.5.3"


